export { Html };
/**
 * This enum contains the most common HTML tags
 */
var Html;
(function (Html) {
    Html["View"] = "view";
    Html["Div"] = "div";
    Html["Span"] = "span";
    Html["Input"] = "input";
    Html["Button"] = "button";
    Html["Textarea"] = "textarea";
    Html["Select"] = "select";
    Html["Option"] = "option";
    Html["Form"] = "form";
    Html["Label"] = "label";
    Html["Img"] = "img";
    Html["A"] = "a";
    Html["B"] = "b";
    Html["Table"] = "table";
    Html["Thead"] = "thead";
    Html["Tbody"] = "tbody";
    Html["Tr"] = "tr";
    Html["Th"] = "th";
    Html["Td"] = "td";
    Html["I"] = "i";
    Html["Ul"] = "ul";
    Html["Li"] = "li";
    Html["Nav"] = "nav";
    Html["Header"] = "header";
    Html["Footer"] = "footer";
    Html["Section"] = "section";
    Html["Article"] = "article";
    Html["Aside"] = "aside";
    Html["H1"] = "h1";
    Html["H2"] = "h2";
    Html["H3"] = "h3";
    Html["H4"] = "h4";
    Html["H5"] = "h5";
    Html["H6"] = "h6";
    Html["P"] = "p";
    Html["Hr"] = "hr";
    Html["Br"] = "br";
    Html["Canvas"] = "canvas";
    Html["Svg"] = "svg";
    Html["Path"] = "path";
    Html["Polygon"] = "polygon";
    Html["Polyline"] = "polyline";
    Html["Circle"] = "circle";
    Html["Ellipse"] = "ellipse";
    Html["Rect"] = "rect";
    Html["Line"] = "line";
    Html["Text"] = "text";
    Html["Tspan"] = "tspan";
    Html["G"] = "g";
    Html["Mask"] = "mask";
    Html["Pattern"] = "pattern";
    Html["Defs"] = "defs";
    Html["Symbol"] = "symbol";
    Html["Use"] = "use";
    Html["Clippath"] = "clipPath";
    Html["Stop"] = "stop";
    Html["LinearGradient"] = "linearGradient";
    Html["RadialGradient"] = "radialGradient";
    Html["Filter"] = "filter";
    Html["Video"] = "video";
})(Html || (Html = {}));
